### ISSUE TITLE
Cron not run with docker-compose

### ISSUE THREAD

**Issue by barryvdh** [Intermesh/docker-groupoffice#10]
I installed the package with docker-compose, but I keep getting this notice:

> The main cron job doesn't appear to be running. Please add a cron job: * * * * * www-data php /usr/local/share/groupoffice/cron.php /etc/groupoffice/config.php

Do I need to manually configure the cron in docker-composer.yml?

**Comment by mschering** [comment]
Hi,

I've updated the README.md with instructions for the cronjob:

https://github.com/Intermesh/docker-groupoffice/blob/master/README.md

**Comment by barryvdh** [comment]
Thanks!
Is the first docker-exec right? Shouldn't it just be: 
```
* * * * * root cd /path/to/docker-groupoffice && docker-compose exec groupoffice php /usr/local/share/groupoffice/cron.php
```

**Comment by barryvdh** [comment]
And also `docker-compose -T`  to make it non-interactive.

**Comment by mschering** [comment]
Sorry, I was a bit too quick with editing the command. You're absolutely right. I've changed it accordingly. Thanks!

**Comment by albertvisuals** [comment]
I am trying to get the cron running without any luck. 
I am using Portainer to deploy the stacks. 

Portainer saves the Yaml file to /var/lib/docker/volumes/portainer_data/_data/compose/12/docker-compose.yml
Where 12 is the id of the group office stack. 

I have tried to add * * * * * root cd /var/lib/docker/volumes/portainer_data/_data/compose/12 && docker compose exec -T groupoffice-groupoffice-1 php /usr/local/share/groupoffice/cron.php
to the cron-tab but I still get the error "no cron running" within group-office. 


groupoffice-groupoffice-1 is the name of the container. 


Anybody an idea how to get this to work?
Thanks a lot!
