### ISSUE TITLE
Docker deployment error: Unknown database 'groupoffice'

### ISSUE THREAD

**Issue by Jogai** [Intermesh/docker-groupoffice#12]
Could not connect to the database. The database returned this error:
SQLSTATE[HY000] [1049] Unknown database 'groupoffice'

If I use mysql as database I can get to the licence step, but then it errors with:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mysql.core_module' doesn't exist

**Comment by mschering** [comment]
Normally the mariadb image creates the database on first load. Can you restart from scratch?

Delete containers and volumes (this destroyes all data!):

docker-compose down -v

Make sure you have the latest images:

docker-compose pull

Start it again:

docker-compose up -d
