### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by Abraka** [Intermesh/docker-groupoffice#14]
Hi, question about licence...Im home user, enthusiast and I like groupoffice, but without "commercial" modules its not that much usable for me. Do you have any licence option for home self hosters(no commercial use) or would you consider it? Something like license for 10-20 family members for 50-100€ ?

**Comment by mschering** [comment]
Sorry, we only offer it as business license. Which features are you missing for a home user?

**Comment by Abraka** [comment]
Well, document editing and search is a must today, its a just a standart. In my case I already have onlyoffice server up and using it, so abillity to connect it to GO should be possible for end users. Projects with time tracking could by useful for home user for example repair home utilities, bulding and so on. Support tickets, billing, video calls, newsletter, studio arent that usefull for home user IMO. 
Just for example, how one of the bigger player doing this...onlyoffice offers their sw completelly free for 5 users in case of private use. All functions except document editing in mobile client. Its clever and simple, because with 5 user limitation you effectivelly  elliminate all type of "corporate" use. In your case and countless others, its just typical crypleware/half-functioning product. Maybe a onlyoffice way would be a better way for GO, but who knows. Ofcourse I can get with bloatware project like nextcloud, but I tried GO office demo(full version) and it was fast, relatively simple for using so I just was intersted in using it for few home members. But if its only for business, its not for home use in this current price range, considering other options like onlyoffice, nextcloud etc. Anyway thx for answer.

**Comment by Abraka** [comment]
.
