### ISSUE TITLE
Tag with actual groupoffice version

### ISSUE THREAD

**Issue by vwout** [Intermesh/docker-groupoffice#15]
The image published on Docker hub is tagged with the major and minor version (and latest for 6.7). All releases of groupoffice always also use a patch version.
The [Dockerfile](https://github.com/Intermesh/docker-groupoffice/blob/master/Dockerfile#L75C1-L75C19) also uses this x.y.z version (though fixed to a specific release rather than the actually used version).

Would it be possible to (next to latest and 6.x) to also tag with the actual groupoffice release to make it easier to pin the release in a compose file?

**Comment by mschering** [comment]
Thanks, we'lll start tagging the patch versions from now on.
