### ISSUE TITLE
Sorry, an error occurred: Undefined array key "otpauthenticator"

### ISSUE THREAD

**Issue by jh197033** [Intermesh/docker-groupoffice#16]
I have just rebuilt my docker image using the latest version (my previous groupoffice was 6.6) and it asks me to upgrade the database which i did but then on the login screen after trying to login i get the error:

Sorry, an error occurred: Undefined array key "otpauthenticator"

Do I need to install something?

**Comment by mschering** [comment]
The module googleauthenticator was renamed to otpauthenticator. It looks like the cache wasn't cleared. Can you try running /install again?

**Comment by jh197033** [comment]
Now i am getting error messages like:

Upgrade output will be logged into: log/upgrade/20230823_075853.log

Skipping module otp because it's not available.
Rebuilding cache
Registering all entities
Error: PDOException in /usr/local/share/groupoffice/go/core/db/Statement.php at line 127: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Tasklist' for key 'clientName'

**Comment by mschering** [comment]
Sorry, I'm not sure why this happens. Please contact us if you need support.
