### ISSUE TITLE
SourceGuardian Loader - This script is expired

### ISSUE THREAD

**Issue by mirkoozekker** [Intermesh/docker-groupoffice#17]
I cloned this repo, ran `docker-compose up -d` and startet the installation-process in the browser. After entering the admin-data, the installing-screen shows up a second and afterwards I get the exception mentioned above.
When I use the image without "testing", everything works fine, except it seems to be the professional edition.
What can I do?

Uncaught exception: ErrorException in /usr/local/share/groupoffice/go/modules/business/finance/convert/Mt940.php at line 2: Uncaught ErrorException: SourceGuardian Loader - This script is expired. Please contact the author of the script regarding this problem. Error code [09] in /usr/local/share/groupoffice/go/modules/business/finance/convert/Mt940.php:2
Stack trace:
#0 [internal function]: go\core\ErrorHandler::errorHandler(256, 'SourceGuardian ...', '/usr/local/shar...', 2)
#1 /usr/local/share/groupoffice/go/modules/business/finance/convert/Mt940.php(2): sg_load('590A3FEBC7C4FCF...')
#2 /usr/local/share/groupoffice/vendor/composer/ClassLoader.php(444): include('/usr/local/shar...')
#3 /usr/local/share/groupoffice/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/usr/local/shar...')
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('go\\modules\\busi...')
#5 /usr/local/share/groupoffice/go/core/util/ClassFinder.php(223): class_exists('go\\modules\\busi...')
#6 /usr/local/share/groupoffice/go/core/util/ClassFinder.php(238): go\core\util\ClassFinder->folderToClassNames(Object(go\core\fs\Folder), 'go\\modules\\busi...')
#7 /usr/local/share/groupoffice/go/core/util/ClassFinder.php(238): go\core\util\ClassFinder->folderToClassNames(Object(go\core\fs\Folder), 'go\\modules\\busi...')
#8 /usr/local/share/groupoffice/go/core/util/ClassFinder.php(238): go\core\util\ClassFinder->folderToClassNames(Object(go\core\fs\Folder), 'go\\modules\\busi...')
#9 /usr/local/share/groupoffice/go/core/util/ClassFinder.php(92): go\core\util\ClassFinder->folderToClassNames(Object(go\core\fs\Folder), 'go\\modules')
#10 /usr/local/share/groupoffice/go/core/util/ClassFinder.php(153): go\core\util\ClassFinder->find()
#11 /usr/local/share/groupoffice/go/core/util/ClassFinder.php(113): go\core\util\ClassFinder->findBy(Object(Closure))
#12 /usr/local/share/groupoffice/go/core/Module.php(86): go\core\util\ClassFinder->findByParent('go\\core\\Module')
#13 /usr/local/share/groupoffice/go/core/Installer.php(191): go\core\Module::findAvailable()
#14 /usr/local/share/groupoffice/go/core/Installer.php(161): go\core\Installer->getAutoInstallModules()
#15 /usr/local/share/groupoffice/install/install.php(84): go\core\Installer->install(Array)
#16 {main}
  thrown at 2023-09-13T13:03:24+00:00

**Comment by MrShippeR** [comment]
+1 with this problem.

**Comment by danfossi** [comment]
Same here but with different exception:

```
Uncaught exception: ErrorException in /usr/local/share/groupoffice/go/modules/business/finance/controller/Debtor.php at line 2: Uncaught ErrorException: SourceGuardian Loader - This script is expired. Please contact the author of the script regarding this problem. Error code [09] in /usr/local/share/groupoffice/go/modules/business/finance/controller/Debtor.php:2

Stack trace:
#0 [internal function]: go\core\ErrorHandler::errorHandler(256, 'SourceGuardian ...', '/usr/local/shar...', 2)

#1 /usr/local/share/groupoffice/go/modules/business/finance/controller/Debtor.php(2): sg_load('590A3FEBC7C4FCF...')

#2 /usr/local/share/groupoffice/vendor/composer/ClassLoader.php(444): include('/usr/local/shar...')

#3 /usr/local/share/groupoffice/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/usr/local/shar...')

#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('go\\modules\\busi...')

#5 /usr/local/share/groupoffice/go/core/util/ClassFinder.php(223): class_exists('go\\modules\\busi...')

#6 /usr/local/share/groupoffice/go/core/util/ClassFinder.php(238): go\core\util\ClassFinder->folderToClassNames(Object(go\core\fs\Folder), 'go\\modules\\busi...')

#7 /usr/local/share/groupoffice/go/core/util/ClassFinder.php(238): go\core\util\ClassFinder->folderToClassNames(Object(go\core\fs\Folder), 'go\\modules\\busi...')

#8 /usr/local/share/groupoffice/go/core/util/ClassFinder.php(238): go\core\util\ClassFinder->folderToClassNames(Object(go\core\fs\Folder), 'go\\modules\\busi...')

#9 /usr/local/share/groupoffice/go/core/util/ClassFinder.php(92): go\core\util\ClassFinder->folderToClassNames(Object(go\core\fs\Folder), 'go\\modules')

#10 /usr/local/share/groupoffice/go/core/util/ClassFinder.php(153): go\core\util\ClassFinder->find()

#11 /usr/local/share/groupoffice/go/core/util/ClassFinder.php(113): go\core\util\ClassFinder->findBy(Object(Closure))

#12 /usr/local/share/groupoffice/go/core/Module.php(86): go\core\util\ClassFinder->findByParent('go\\core\\Module')

#13 /usr/local/share/groupoffice/go/core/Installer.php(191): go\core\Module::findAvailable()

#14 /usr/local/share/groupoffice/go/core/Installer.php(161): go\core\Installer->getAutoInstallModules()

#15 /usr/local/share/groupoffice/install/install.php(84): go\core\Installer->install(Array)

#16 {main}

thrown at 2023-10-02T09:29:01+00:00
```

**Comment by mschering** [comment]
Please don't use the "testing" tag. I was testing sourceguardian with the trial license back then. Just use the "6.8" or latest image.

**Comment by mschering** [comment]
Sorry, I just noticed the docker compose.yml file contained the testing tag. I've changed this to 6.8.
