### ISSUE TITLE
Groupoffice is not compatible with PHP 8.2 but uses it in Dockerfile

### ISSUE THREAD

**Issue by JodliDev** [Intermesh/docker-groupoffice#19]
Group office seems to install PHP 8.2 in its docker Dockerfile. But Groupoffice uses version 4.4 of Sabre\DAV which is not compatible with PHP 8.2 (This seems to be fixed in sabre\DAV version 4.5).

This causes (at least) the following errors:

When adding the addressbook to a new client (thunderbird in my case) the error responds with a 500 error and internally throws:
```
[Sun Mar 03 16:07:39 2024] [notice] [pid 25] [client 172.24.0.1:53152] ErrorException in /usr/local/share/groupoffice/vendor/sabre/dav/lib/CardDAV/Xml/Request/AddressBookMultiGetReport.php at line 104: Creation of dynamic property Sabre\\CardDAV\\Xml\\Request\\AddressBookMultiGetReport::$addressDataProperties is deprecated
```

(Probably) The same error is caused when trying to export the addressbook:
```
Creation of dynamic property go\modules\community\addressbook\convert\VCard::$tempFile is deprecated
```

You can find more information here:
https://github.com/sabre-io/dav/issues/1474

**Comment by mschering** [comment]
Which image are you using? I found and fixed some issues but couldn't find your last error. This property exists:

go\modules\community\addressbook\convert\VCard::$tempFile

PS: Please report bugs at the main project intermesh/groupoffice.
