### ISSUE TITLE
Can't sync with ActiveSync - 6.8.61

### ISSUE THREAD

**Issue by olegchensky** [Intermesh/docker-groupoffice#22]
I receive:

StateObject implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary)

**Comment by theknigge** [comment]
Same issue
Version: 6.8.61

**Comment by olegchensky** [comment]
Please update the release too

**Comment by mschering** [comment]
It was released today already

**Comment by olegchensky** [comment]
Works fine, thanks!
