### ISSUE TITLE
Make memory_limit persistent

### ISSUE THREAD

**Issue by julyusito** [Intermesh/docker-groupoffice#3]
Hello,

I am trying to change default values for memory_limit in the /usr/local/etc/php/php.ini but they lost after restart the container.  I also try creating the /usr/local/etc/php/conf.d/memory-limit.ini file, without success.
memory_limit=1024M

I've create an info.php with the phpinfo() function, but the memory_limit value is always 128M

How can I make this values persistent?

Thanks!

**Comment by julyusito** [comment]
Hello,

It works, the /usr/local/etc/php/conf.d/memory-limit.ini file works it was permissions.
-rw-r--r-- 1 root root 63 Feb  2 11:51 memory-limit.ini 

All PHP variables can set there, it just need restart the container.
Just put this file in there, every time container being re-created.

To test the configuration:
Create a file info.php with this lines in /usr/local/share/groupoffice/install directory
<?php
phpinfo();
?>

Set the permissions:
chown www-data:www-data /usr/local/share/groupoffice/install/info.php
chmod 644 /usr/local/share/groupoffice/install/info.php

And test the page:
https://go.example.com/install/info.php

Search for the variable in the result page

Ended the test, hide the directory:
chown root:root /usr/local/share/groupoffice/install
chmod 444 /usr/local/share/groupoffice/install

Regards.

**Comment by mschering** [comment]
Thanks, I've also set some higher default values:

memory_limit	256M
post_max_size	1000M
upload_max_filesize	1000M
