### ISSUE TITLE
ActiveSync Calendar Sync

### ISSUE THREAD

**Issue by cm91** [Intermesh/docker-groupoffice#6]
Hi,

i'm using the latest Docker Image and everything seems to work properly

but i have one question regarding calendar sync via ActiveSync:

I have multiple calendars created in my account. On my Device (iPhone) i can see all events and appointments, but the calendars
are merged to a object called "Calendar" which contains all the events of my calendars. I guess this is expected by default.

Is there any way to sync the calendars individually, so that i can add events to a specific calendar or hide specific calendars on my phone without removing it from the synced objects in groupoffice?

Thanks in advance,
Christian

**Comment by mschering** [comment]
Thanks. this functionality will come in the next 6.5 release!
